# Generated by Django 4.2.6 on 2023-10-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('paswword', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='seller/')),
                ('accnumber', models.CharField(max_length=30)),
                ('loginid', models.CharField(max_length=30)),
                ('company_name', models.CharField(default='', max_length=20)),
                ('bank_name', models.CharField(default='', max_length=20)),
                ('bank_branch', models.CharField(default='', max_length=20)),
                ('ifsc', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
